<a href="https://colab.research.google.com/github/rr1989/capstone-project-recommendation-system-by-rr/blob/main/Final_Capstone_Recommendation_System_by_Rakesh_Sept_9th.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recommendation System Notebook
- User based recommendation
- User based prediction & evaluation
- Item based recommendation
- Item based prediction & evaluation

Different Approaches to develop Recommendation System -

1. Demographich based Recommendation System

2. Content Based Recommendation System

3. Collaborative filtering Recommendation System

In [1]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Reading ratings file from GitHub. # MovieLens
ratings = pd.read_csv('sample30.csv' , encoding='latin-1')
ratings.head()

id            brand  ... reviews_username user_sentiment
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3  AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4  AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative

[5 rows x 15 columns]

In [3]:
ratings = ratings[["reviews_username","name","reviews_rating"]]

## Dividing the dataset into train and test

In [4]:
# Test and Train split of the dataset.
from sklearn.model_selection import train_test_split
train, test = train_test_split(ratings, test_size=0.30, random_state=31)

In [5]:
print(train.shape)
print(test.shape)

(21000, 3)
(9000, 3)


In [6]:
train

reviews_username  ... reviews_rating
11155         gor05751  ...              5
22114          annavsl  ...              4
26218         bluenose  ...              5
18966             kiki  ...              5
29999        kcoopxoxo  ...              5
...                ...  ...            ...
3735              mary  ...              5
14946           mwah25  ...              5
27518            lilym  ...              4
26640              kim  ...              5
21202          nurse12  ...              1

[21000 rows x 3 columns]

In [7]:
train = train.groupby(by=["reviews_username",'name']).mean()
train

reviews_rating
reviews_username name                                                              
00dog3           Chex Muddy Buddies Brownie Supreme Snack Mix                   4.0
00sab00          Mike Dave Need Wedding Dates (dvd + Digital)                   1.0
01impala         Godzilla 3d Includes Digital Copy Ultraviolet 3...             3.0
0325home         Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
06stidriver      Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
...                                                                             ...
zulaa118         Red (special Edition) (dvdvideo)                               5.0
zxcsdfd          Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
zxjki            Clorox Disinfecting Wipes Value Pack Scented 15...             2.0
zyiah4           Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
zzdiane          My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Dig...             5.0

[19753 rows x 1 columns]

In [8]:
train['reviews_rating']

reviews_username  name                                                           
00dog3            Chex Muddy Buddies Brownie Supreme Snack Mix                       4.0
00sab00           Mike Dave Need Wedding Dates (dvd + Digital)                       1.0
01impala          Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd    3.0
0325home          Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total          5.0
06stidriver       Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total          5.0
                                                                                    ... 
zulaa118          Red (special Edition) (dvdvideo)                                   5.0
zxcsdfd           Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total          5.0
zxjki             Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total          2.0
zyiah4            Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total          5.0
zzdiane           My Big Fat

In [9]:
train.reset_index(level=0, inplace=True)


In [10]:
train.reset_index(level=0, inplace=True)

In [11]:
train

name  ... reviews_rating
0           Chex Muddy Buddies Brownie Supreme Snack Mix  ...            4.0
1           Mike Dave Need Wedding Dates (dvd + Digital)  ...            1.0
2      Godzilla 3d Includes Digital Copy Ultraviolet ...  ...            3.0
3      Clorox Disinfecting Wipes Value Pack Scented 1...  ...            5.0
4      Clorox Disinfecting Wipes Value Pack Scented 1...  ...            5.0
...                                                  ...  ...            ...
19748                   Red (special Edition) (dvdvideo)  ...            5.0
19749  Clorox Disinfecting Wipes Value Pack Scented 1...  ...            5.0
19750  Clorox Disinfecting Wipes Value Pack Scented 1...  ...            2.0
19751  Clorox Disinfecting Wipes Value Pack Scented 1...  ...            5.0
19752  My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Di...  ...            5.0

[19753 rows x 3 columns]

In [12]:
# Pivot the train ratings' dataset into matrix format in which columns are product name and the rows are username.
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(0)

df_pivot.head(3)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                       0.0
00sab00                                                         0.0              ...                                       0.0
01impala                                                        0.0              ...                                       0.0

[3 rows x 252 columns]

In [13]:
df_pivot['Chex Muddy Buddies Brownie Supreme Snack Mix']

reviews_username
00dog3         4.0
00sab00        0.0
01impala       0.0
0325home       0.0
06stidriver    0.0
              ... 
zulaa118       0.0
zxcsdfd        0.0
zxjki          0.0
zyiah4         0.0
zzdiane        0.0
Name: Chex Muddy Buddies Brownie Supreme Snack Mix, Length: 18252, dtype: float64

### Creating dummy train & dummy test dataset
These dataset will be used for prediction 
- Dummy train will be used later for prediction of the product which has not been rated by the user. To ignore the product rated by the user, we will mark it as 0 during prediction. The product not rated by user is marked as 1 for prediction in dummy train dataset. 

- Dummy test will be used for evaluation. To evaluate, we will only make prediction on the product rated by the user. So, this is marked as 1. This is just opposite of dummy_train.

In [14]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [15]:
# The products not rated by user is marked as 1 for prediction. 
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [16]:
# Convert the dummy train dataset into matrix format.
dummy_train = dummy_train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(1)

In [17]:
dummy_train.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          1.0              ...                                       1.0
00sab00                                                         1.0              ...                                       1.0
01impala                                                        1.0              ...                                       1.0
0325home                                                        1.0              ...                                       1.0
06stidriver                                                     1.0              ...                                       1.0

[5 rows x 252 columns]

**Cosine Similarity**

Cosine Similarity is a measurement that quantifies the similarity between two vectors [Which is Rating Vector in this case] 

**Adjusted Cosine**

Adjusted cosine similarity is a modified version of vector-based similarity where we incorporate the fact that different users have different ratings schemes. In other words, some users might rate items highly in general, and others might give items lower ratings as a preference. To handle this nature from rating given by user , we subtract average ratings for each user from each user's rating for different movies.



# User Similarity Matrix

## Using Cosine Similarity

In [18]:
from sklearn.metrics.pairwise import pairwise_distances

# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_pivot, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [19]:
user_correlation.shape

(18252, 18252)

## Using adjusted Cosine 

### Here, we are not removing the NaN values and calculating the mean only for the products rated by the user

In [20]:
# Create a user-movie matrix.
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
)

In [21]:
df_pivot.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN
00sab00                                                         NaN              ...                                       NaN
01impala                                                        NaN              ...                                       NaN
0325home                                                        NaN              ...                                       NaN
06stidriver                                                     NaN              ...                                       NaN

[5 rows x 252 columns]

### Normalising the rating of the product for each user around 0 mean

In [22]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [23]:
df_subtracted.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN
00sab00                                                         NaN              ...                                       NaN
01impala                                                        NaN              ...                                       NaN
0325home                                                        NaN              ...                                       NaN
06stidriver                                                     NaN              ...                                       NaN

[5 rows x 252 columns]

### Finding cosine similarity

In [24]:
from sklearn.metrics.pairwise import pairwise_distances

In [25]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Prediction - User User

Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, ignoring the correlation for values less than 0. 

In [26]:
user_correlation[user_correlation<0]=0
user_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Rating predicted by the user (for product rated as well as not rated) is the weighted sum of correlation with the product rating (as present in the rating dataset). 

In [27]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
user_predicted_ratings.shape

(18252, 252)

Since we are interested only in the products not rated by the user, we will ignore the products rated by the user by making it zero. 

In [29]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                       0.0
00sab00                                                         0.0              ...                                       0.0
01impala                                                        0.0              ...                                       0.0
0325home                                                        0.0              ...                                       0.0
06stidriver                                                     0.0              ...                                       0.0

[5 rows x 252 columns]

In [30]:
for i in user_final_rating["100:Complete First Season (blu-Ray)"]:
  if i > 0:
    print(i)

10.177320760990225
11.850259125235349
3.1499166132335263
4.702847075210474
0.13572531765245
1.449821866091257
13.254930542653748
3.061862178478973
2.206474848722799
1.5649528464044595
4.211094289736992
0.9241242301415896
3.75
4.979153908129584
11.92060168682202
2.0864972611714134
5.354139110507989
2.2064748487227988
12.113174883553366
10.177320760990225
1.4548516392823951
0.42920113993159914
5.520620726159658
1.4548516392823951
3.860864048875153
0.150717690849421
1.9358541225631414
10.177320760990225
1.8772769422910538
0.6554709342475236
4.514153164245808
5.191158065552841
5.1754945283363
3.1847181262706004
12.683592458568668
4.702847075210474
3.1499166132335263
1.9358541225631414
10.177320760990225
5.520620726159658
0.42920113993159914
8.721060460284406
2.066404598251252
3.87728290708791
10.830127018922191
10.177320760990225
3.6410688066865524
12.464621406529922
2.7669929526473327
7.963495319798332
1.9358541225631414
0.17522063164221668
1.0106073612822533
6.211778791712499
10.17732076

### Finding the top 5 recommendation for the *user*

In [31]:
# Take the user ID as input.
user_input = (input("Enter your user name"))
print(user_input)

Enter your user name06stidriver
06stidriver


In [32]:
user_final_rating.head(2)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                       0.0
00sab00                                                         0.0              ...                                       0.0

[2 rows x 252 columns]

In [33]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)#[0:5]
d

name
Yes To Grapefruit Rejuvenating Body Wash                         0.0
Elvis Presley - Girl Happy (cd)                                  0.0
Head & Shoulders Classic Clean Conditioner                       0.0
Hawaiian Punch Berry Limeade Blast Juice                         0.0
Happy Tot Apple and Butternut Squash                             0.0
                                                                ... 
Olay Moisturizing Lotion For Sensitive Skin                      0.0
Ogx Conditioner, Hydrating Teatree Mint                          0.0
Ogx Anti-breakage Keratin Oil 3 Minute Miraculous Recovery       0.0
Noosa Honey Yogurt                                               0.0
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest    0.0
Name: 06stidriver, Length: 252, dtype: float64

In [34]:
#Mapping with Movie Title / Genres 
#movie_mapping = pd.read_csv('https://raw.githubusercontent.com/antrikshsaxena/NLPCapstone/main/movies.csv')
#movie_mapping.head()

In [35]:
#d = pd.merge(d,movie_mapping,left_on='movieId',right_on='movieId', how = 'left')
#d.head()

# Evaluation - User User 

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the product already rated by the user insead of predicting it for the product not rated by the user. 

In [36]:
# Find out the common users of test and train dataset.
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(2029, 3)

In [37]:
common.head()

reviews_username  ... reviews_rating
20634           girlie  ...              5
26479       kasheville  ...              1
15098           arlene  ...              5
17968            mimi3  ...              5
28020       movielover  ...              5

[5 rows x 3 columns]

In [38]:
# convert into the user-product matrix.
common_user_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [39]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)

In [40]:
df_subtracted.head(1)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN

[1 rows x 252 columns]

In [41]:

user_correlation_df['reviews_username'] = df_subtracted.index
user_correlation_df.set_index('reviews_username',inplace=True)
user_correlation_df.head()

0      1      2      3      ...  18248  18249  18250  18251
reviews_username                              ...                            
00dog3              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
00sab00             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
01impala            0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
0325home            0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
06stidriver         0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 18252 columns]

In [42]:
common.head(1)

reviews_username  ... reviews_rating
20634           girlie  ...              5

[1 rows x 3 columns]

In [43]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_subtracted.index.tolist()


user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [44]:
user_correlation_df_1.shape

(1728, 18252)

In [45]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [46]:
user_correlation_df_3 = user_correlation_df_2.T

In [47]:
user_correlation_df_3.head()

00sab00  1234  1234asdf  ...  zburt5  zebras  zmom
reviews_username                           ...                      
00sab00               0.0   0.0       0.0  ...     0.0     0.0   0.0
1234                  0.0   0.0       0.0  ...     0.0     0.0   0.0
1234asdf              0.0   0.0       0.0  ...     0.0     0.0   0.0
123charlie            0.0   0.0       0.0  ...     0.0     0.0   0.0
1943                  0.0   0.0       0.0  ...     0.0     0.0   0.0

[5 rows x 1728 columns]

In [48]:
user_correlation_df_3.shape

(1728, 1728)

In [49]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [50]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').fillna(0)

In [51]:
dummy_test.shape

(1728, 126)

In [52]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [53]:
common_user_predicted_ratings.head(2)

name              100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                       ...                                          
00sab00                                           0.0  ...                                       0.0
1234                                              0.0  ...                                       0.0

[2 rows x 126 columns]

Calculating the RMSE for only the products rated by user. For RMSE, normalising the rating to (1,5) range.

In [54]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:375: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:376: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [55]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [56]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [57]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

2.498437231297542


## Using Item similarity

# Item Based Similarity




Taking the transpose of the rating matrix to normalize the rating around the mean for different product name. In the user based similarity, we had taken mean for each user instead of each *product*. 

In [58]:
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).T

df_pivot.head()

reviews_username                                    00dog3  ...  zzdiane
name                                                        ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     NaN  ...      NaN
100:Complete First Season (blu-Ray)                    NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...     NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                 NaN  ...      NaN
4C Grated Parmesan Cheese 100% Natural 8oz Shaker      NaN  ...      NaN

[5 rows x 18252 columns]

Normalising the product rating for each product for using the Adujsted Cosine

In [59]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [60]:
df_subtracted.head()

reviews_username                                    00dog3  ...  zzdiane
name                                                        ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     NaN  ...      NaN
100:Complete First Season (blu-Ray)                    NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...     NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                 NaN  ...      NaN
4C Grated Parmesan Cheese 100% Natural 8oz Shaker      NaN  ...      NaN

[5 rows x 18252 columns]

Finding the cosine similarity using pairwise distances approach




In [61]:
from sklearn.metrics.pairwise import pairwise_distances

In [62]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.          0.         ... -0.00657044  0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.         -0.00657044  0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]


Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [63]:
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [64]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.02352264, 0.        ,
        0.        ],
       [0.        , 0.00117139, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.04848007, 0.        , ..., 0.        , 0.        ,
        0.00338607],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00062229, 0.00063779,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00155571, 0.00159447,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.03252811, 0.02124867,
        0.        ]])

In [65]:
item_predicted_ratings.shape

(18252, 252)

In [66]:
dummy_train.shape

(18252, 252)

### Filtering the rating only for the product not rated by the user for recommendation

In [67]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                  0.000000
00sab00                                                         0.0              ...                                  0.000000
01impala                                                        0.0              ...                                  0.003386
0325home                                                        0.0              ...                                  0.000000
06stidriver                                                     0.0              ...                                  0.000000

[5 rows x 252 columns]

### Finding the top 5 recommendation for the *user*






In [68]:
# Take the user name as input
user_input = (input("Enter your user name"))
print(user_input)

Enter your user name06stidriver
06stidriver


In [69]:
# Recommending the Top 5 products to the user.
d = item_final_rating.loc[user_input].sort_values(ascending=False)#[0:5]
d

name
Clorox Disinfecting Bathroom Cleaner                                              0.766556
Newman's Own Organics Licorice Twist, Black 5oz                                   0.022144
L'or233al Paris Elvive Extraordinary Clay Rebalancing Conditioner - 12.6 Fl Oz    0.019876
Sea Gull Lighting Six Light Bath Sconce/vanity - Brushed Nickel                   0.019500
Mrs. Meyer's174 Lemon Verbena Laundry Scent Booster - 18oz                        0.014756
                                                                                    ...   
Naturtint Nutrideep Multiplier Protective Cream                                   0.000000
Nature's Path Flax Plus Maple Pecan Crunch Cereal                                 0.000000
Nature's Path Chunky Chocolate Peanut Chewy Granola Bars                          0.000000
Musselman Apple Sauce, Cinnamon, 48oz                                             0.000000
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest                     0.0

In [70]:
#Mapping with Movie Title / Genres 
#movie_mapping = pd.read_csv('https://raw.githubusercontent.com/antrikshsaxena/NLPCapstone/main/movies.csv', encoding='latin-1')

In [71]:
#d = pd.merge(d,movie_mapping,left_on='movieId',right_on='movieId',how = 'left')
#d.head()

In [72]:
#train_new = pd.merge(train,movie_mapping,left_on='movieId',right_on='movieId',how='left')
#train_new[train_new.userId == 1] .head()

# Evaluation - Item Item

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the product already rated by the user insead of predicting it for the product not rated by the user. 

In [73]:
test.columns

Index(['reviews_username', 'name', 'reviews_rating'], dtype='object')

In [74]:
common =  test[test.name.isin(train.name)]
common.shape

(8978, 3)

In [75]:
common.head(4)

reviews_username  ... reviews_rating
4332          sansname  ...              5
3434      jennypstrong  ...              5
20634           girlie  ...              5
26479       kasheville  ...              1

[4 rows x 3 columns]

In [76]:
common_item_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [77]:
common_item_based_matrix.shape

(199, 8371)

In [78]:
item_correlation_df = pd.DataFrame(item_correlation)

In [79]:
item_correlation_df.head(1)

0    1    2    3    4    5    6    ...  245  246  247  248  249  250  251
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[1 rows x 252 columns]

In [80]:
item_correlation_df['name'] = df_subtracted.index
item_correlation_df.set_index('name',inplace=True)
item_correlation_df.head()

0    1    ...  250  251
name                                                          ...          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  1.0  0.0  ...  0.0  0.0
100:Complete First Season (blu-Ray)                 0.0  1.0  ...  0.0  0.0
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  ...  0.0  0.0
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  ...  0.0  0.0
4C Grated Parmesan Cheese 100% Natural 8oz Shaker   0.0  0.0  ...  0.0  0.0

[5 rows x 252 columns]

In [81]:
list_name = common.name.tolist()

In [82]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [83]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [84]:
item_correlation_df_3.head()

0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
name                                                                                                               ...                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                1.0              ...                                       0.0
100:Complete First Season (blu-Ray)                                                               0.0              ...                                       0.0
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0              ...                                       0.0
Africa's Best No-Lye Dual Conditioning Relaxer ...                                                0.0              ...                                       0.0
Alberto VO5 Salon Series Smooth Plus Sleek Shampoo                                                0.0              ...                                       0.0

[5 rows x 199 columns]

In [85]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.08080011, 0.06464009, ..., 0.01395515, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.01951687, 0.        , 0.        , ..., 0.        , 0.00155571,
        0.00124457],
       [0.0127492 , 0.        , 0.        , ..., 0.        , 0.00159447,
        0.00127557],
       [0.        , 0.00564345, 0.00451476, ..., 0.        , 0.        ,
        0.        ]])

In [86]:
common_item_predicted_ratings.shape

(199, 8371)

Dummy test will be used for evaluation. To evaluate, we will only make prediction on the products rated by the user. So, this is marked as 1. This is just opposite of dummy_train



In [87]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

The products not rated is marked as 0 for evaluation. And make the item- item matrix representaion.


In [88]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [89]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:375: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:376: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [90]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [91]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

3.5599247722439755


Item-Item coloborative approach is better as we are getting the correct result

